lexik_jwt_authentication:
    # Chemins vers les fichiers (résolus via env)
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'   # vide si clé non chiffrée
    token_ttl: 3600
